/*
 * Fichas completas dos 12 arquétipos de marca.
 * Base conceitual (desejo, meta, medo, estratégia, dom, armadilha e lema):
 *   Margaret Mark & Carol S. Pearson, "O Herói e o Fora-da-Lei" (2001/2003) e
 *   Carol S. Pearson, "O Despertar do Herói Interior" (1991).
 * Tom de voz e vocabulário: guias de branding de Scott Jeffrey, Ignyte e Amper (ver FONTES).
 * Estilo de roupa: sistema dos 7 estilos universais aplicado a arquétipos (Priscila Citera, Vestindo Autoestima).
 * Frases típicas, postura em vídeo e ideias de conteúdo: aplicação prática da 3P's Produções a partir dessas bases.
 */
window.PERFIS = {
  IN: {
    lema: "Livre para ser você e eu.",
    essencia: "Acredita que a vida pode ser simples, boa e honesta. Transmite confiança pela transparência, pela leveza e pela sensação de que está tudo bem.",
    desejo: "Viver no “paraíso”: ser feliz, em segurança e em paz.",
    meta: "Ser feliz e fazer o certo.",
    medo: "Fazer algo errado e ser punido; decepcionar quem confia.",
    estrategia: "Fazer as coisas do jeito certo, com simplicidade e boa-fé.",
    dom: "Fé, otimismo, pureza de intenção.",
    armadilha: "Ingenuidade, negação dos problemas e ficar sem graça por excesso de doçura.",
    personalidade: ["Otimista", "Honesto", "Leve", "Confiável", "Simples", "Esperançoso"],
    tom: "Positivo, transparente, acolhedor e simples. Frases curtas, sem jargão e sem ironia.",
    usa: ["simples", "natural", "leve", "de verdade", "bem-estar", "com carinho"],
    evita: ["sarcasmo", "termos técnicos", "tom agressivo de venda", "promessas exageradas"],
    frases: ["“Não precisa complicar.”", "“Fiz do jeito certo, pode confiar.”", "“Vai dar tudo certo.”", "“O simples bem feito funciona.”", "“Aqui é tudo às claras.”"],
    roupas: "Estilo romântico com base tradicional: peças confortáveis e limpas. Branco, off-white, azul-claro, tons pastel. Algodão, linho, malhas macias. Poucos acessórios, delicados.",
    postura: "Sorriso aberto, fala pausada, gestos suaves. Em vídeo: luz natural e abundante, fundo claro, cenário organizado e sem excessos.",
    posicionamento: "“O jeito honesto e descomplicado de resolver.” Ganha pela confiança e pela tranquilidade, não pelo preço nem pelo status.",
    conteudo: ["Rotina real e tranquila do trabalho", "Depoimentos sinceros de clientes", "Dicas simples que qualquer pessoa aplica", "Mensagens de esperança e gratidão"],
    marcas: "Dove, Coca-Cola, Natura (linha Mamãe e Bebê)",
    cuidado: "Não negar os problemas do cliente. Mostre que você entende a dificuldade antes de oferecer leveza."
  },
  EX: {
    lema: "Não me prenda.",
    essencia: "Busca liberdade e autenticidade. Quer descobrir quem é explorando o mundo, e convida o público a sair do óbvio.",
    desejo: "Liberdade para descobrir quem é, explorando o mundo.",
    meta: "Viver uma vida mais autêntica e plena.",
    medo: "Ficar preso, se conformar, sentir o vazio interior.",
    estrategia: "Viajar, buscar o novo, fugir do tédio.",
    dom: "Autonomia, ambição, fidelidade à própria essência.",
    armadilha: "Vagar sem rumo, não se comprometer, virar um desajustado.",
    personalidade: ["Curioso", "Independente", "Inquieto", "Autêntico", "Corajoso", "Desbravador"],
    tom: "Curioso, aberto e inspirador. Fala em primeira pessoa, conta experiências vividas, usa verbos de movimento.",
    usa: ["descobrir", "caminho", "liberdade", "novo", "de verdade", "vamos"],
    evita: ["regras rígidas", "linguagem corporativa", "tom de sala de aula", "promessas de conforto"],
    frases: ["“Bora descobrir juntos?”", "“Não existe um único caminho.”", "“Eu precisava ver isso com meus próprios olhos.”", "“Sai da caixa.”", "“A melhor parte é a jornada.”"],
    roupas: "Estilo natural/esportivo: peças funcionais, que aguentam movimento. Tons terrosos, verde-oliva, cáqui, azul-jeans. Linho, algodão cru, couro, tecidos técnicos. Botas, mochila, relógio robusto.",
    postura: "Em movimento, câmera na mão, cenário externo. Fala enquanto caminha e mostra o lugar. Olhar para o horizonte, gestos abertos.",
    posicionamento: "“O caminho que ninguém te mostrou.” Diferencia-se por autenticidade e experiência própria, não por tradição.",
    conteudo: ["“Um dia comigo” e bastidores em campo", "Descobertas e testes em primeira pessoa", "Lugares, fornecedores e histórias pouco conhecidas", "Diário de viagem ou de processo"],
    marcas: "The North Face, Jeep, Patagonia, National Geographic",
    cuidado: "Liberdade demais vira falta de foco. Mantenha uma linha editorial clara e uma oferta fácil de entender."
  },
  SA: {
    lema: "A verdade liberta.",
    essencia: "Quer entender o mundo e ajudar os outros a entendê-lo. Ganha autoridade pela clareza, pelo método e pela profundidade.",
    desejo: "Descobrir a verdade.",
    meta: "Usar a inteligência e a análise para compreender o mundo.",
    medo: "Ser enganado, ser ignorante, agir por desinformação.",
    estrategia: "Buscar informação, conhecimento e reflexão.",
    dom: "Sabedoria, inteligência, clareza.",
    armadilha: "Estudar para sempre e nunca agir; arrogância intelectual; falar difícil.",
    personalidade: ["Analítico", "Curioso", "Calmo", "Criterioso", "Didático", "Reflexivo"],
    tom: "Analítico, didático, preciso e sereno. Explica o porquê, usa dados, exemplos e comparações.",
    usa: ["entenda", "na prática", "o motivo é", "estudo", "evidência", "passo a passo"],
    evita: ["exagero", "promessa milagrosa", "gírias em excesso", "achismo"],
    frases: ["“Deixa eu te explicar o porquê.”", "“Os dados mostram que…”", "“Antes de decidir, entenda isso.”", "“Isso é mito. Isso é verdade.”", "“Vamos por partes.”"],
    roupas: "Estilo tradicional e elegante: peças clássicas de bom corte, sem modismo. Azul-marinho, cinza, marrom, branco, bordô. Lã fria, algodão encorpado, tricô. Óculos, relógio clássico, camisa social ou tricô.",
    postura: "Sentado ou em pé, estável, olhando para a câmera. Fala pausada, gestos que “desenham” a explicação. Cenário: livros, quadro, escritório organizado.",
    posicionamento: "“Quem mais entende do assunto.” Diferencia-se por método, profundidade e credibilidade.",
    conteudo: ["Aulas curtas e explicações", "Mitos e verdades do setor", "Análises de casos e tendências", "Perguntas e respostas"],
    marcas: "Google, TED, BBC, Harvard",
    cuidado: "Explicar demais cansa. Termine cada conteúdo com uma ação prática."
  },
  HE: {
    lema: "Onde há vontade, há um caminho.",
    essencia: "Prova seu valor pela coragem e pela superação. Inspira o público a vencer os próprios limites.",
    desejo: "Provar o próprio valor por meio de atos corajosos.",
    meta: "Dominar o que faz para melhorar o mundo.",
    medo: "Fraqueza, vulnerabilidade, “amarelar”.",
    estrategia: "Ser forte, competente e poderoso.",
    dom: "Competência e coragem.",
    armadilha: "Arrogância e precisar sempre de uma nova batalha.",
    personalidade: ["Determinado", "Corajoso", "Competitivo", "Disciplinado", "Direto", "Resiliente"],
    tom: "Confiante, motivador, direto e enérgico. Verbos de ação, frases curtas e imperativas.",
    usa: ["desafio", "resultado", "superar", "conquista", "foco", "agora"],
    evita: ["hesitação", "“talvez”", "vitimismo", "tom passivo"],
    frases: ["“Não é sobre talento, é sobre disciplina.”", "“Bora pra cima.”", "“Desistir não é opção.”", "“Resultado se constrói.”", "“Você é mais forte do que imagina.”"],
    roupas: "Estilo urbano dramático/esportivo: peças estruturadas, que mostram força e prontidão. Preto, vermelho, azul-royal, cinza-grafite. Tecidos técnicos, sarja, couro. Tênis de performance, relógio esportivo.",
    postura: "Em pé, peito aberto, olhar firme, gestos cortantes. Em vídeo: cortes rápidos, movimento, trilha com energia.",
    posicionamento: "“Quem faz acontecer.” Diferencia-se por performance, resultados comprovados e histórias de superação.",
    conteudo: ["Jornada de superação (antes e depois do esforço)", "Desafios e metas públicas", "Bastidores de treino, preparo e entrega", "Casos de clientes que venceram algo difícil"],
    marcas: "Nike, Gatorade, Under Armour",
    cuidado: "Não transformar o cliente em plateia. O herói da história é ele; você é o mentor."
  },
  RE: {
    lema: "Regras foram feitas para serem quebradas.",
    essencia: "Rompe o que não funciona. Dá voz a quem está incomodado com o jeito tradicional de fazer as coisas.",
    desejo: "Vingança ou revolução: derrubar o que não funciona.",
    meta: "Destruir o que não serve para abrir espaço ao novo.",
    medo: "Ser impotente, irrelevante ou ineficaz.",
    estrategia: "Chocar, desafiar, romper padrões.",
    dom: "Ousadia e liberdade radical.",
    armadilha: "Rebeldia sem propósito, destruição pela destruição.",
    personalidade: ["Ousado", "Provocador", "Independente", "Intenso", "Contestador", "Autêntico"],
    tom: "Provocador, incisivo e inconformado. Opinião forte, contraste “eles fazem assim, eu faço assim”.",
    usa: ["chega de", "ninguém te conta", "quebrar", "de verdade", "sem filtro", "o sistema"],
    evita: ["tom neutro", "pedir permissão", "linguagem institucional", "meio-termo"],
    frases: ["“Ninguém vai te contar isso.”", "“Chega de fazer igual a todo mundo.”", "“Isso é mentira do mercado.”", "“Eu não sigo o manual.”", "“Se incomodou, é porque é verdade.”"],
    roupas: "Estilo criativo com toque dramático: peças que quebram regras. Preto, jeans, couro, contraste forte e um ponto de cor. Jaqueta de couro, camiseta, bota, anéis, tatuagens à mostra.",
    postura: "Olhar direto e desafiador, fala firme, sem sorriso de vendedor. Em vídeo: câmera baixa, contraste alto, cortes secos.",
    posicionamento: "“A alternativa ao jeito tradicional.” Diferencia-se por atacar as dores e os vícios do setor.",
    conteudo: ["Opiniões fortes sobre o mercado", "“O que ninguém te conta sobre…”", "Quebra de mitos e práticas ruins do setor", "Reações e comentários a tendências"],
    marcas: "Harley-Davidson, Diesel, Red Bull",
    cuidado: "Provocar sem propor afasta. Toda crítica precisa vir com a sua alternativa."
  },
  MA: {
    lema: "Eu faço as coisas acontecerem.",
    essencia: "Transforma realidades. Faz o cliente acreditar que o que parecia impossível pode acontecer, e conduz essa transformação.",
    desejo: "Conhecer as leis fundamentais de como o mundo funciona.",
    meta: "Tornar sonhos realidade.",
    medo: "Consequências negativas não intencionais.",
    estrategia: "Desenvolver uma visão e viver de acordo com ela.",
    dom: "Encontrar soluções em que todos ganham; transformar.",
    armadilha: "Tornar-se manipulador; prometer demais.",
    personalidade: ["Visionário", "Carismático", "Intuitivo", "Inspirador", "Estratégico", "Envolvente"],
    tom: "Visionário, inspirador, simbólico e envolvente. Usa metáforas, conta histórias de transformação e fala do “antes e depois”.",
    usa: ["transformar", "imagine", "possível", "virada", "visão", "experiência"],
    evita: ["tom burocrático", "excesso de números frios", "cinismo", "promessas vazias"],
    frases: ["“Imagine se…”", "“Tudo muda quando você enxerga diferente.”", "“O impossível é só o que ainda não foi feito.”", "“Deixa eu te mostrar uma coisa.”", "“A virada começa aqui.”"],
    roupas: "Estilo criativo com urbano dramático: peças com impacto e um detalhe de mistério. Preto, azul-profundo, roxo, vinho, metálicos. Veludo, seda, tecidos com brilho discreto. Um acessório marcante (anel, relógio especial, lenço).",
    postura: "Presença calma e magnética, pausas de efeito, olhar que “prende”. Em vídeo: luz de recorte, sombra, revelações e transições.",
    posicionamento: "“Quem transforma a sua realidade.” Diferencia-se pela experiência e pelo resultado de transformação.",
    conteudo: ["Transformações reais (antes e depois)", "Revelações e bastidores de “como foi feito”", "Visão de futuro do setor", "Experiências imersivas"],
    marcas: "Disney, Apple (lançamentos), Dyson",
    cuidado: "Sustente a magia com prova. Mostre o processo e os resultados reais para não soar manipulador."
  },
  CC: {
    lema: "Todos somos iguais.",
    essencia: "Gente como a gente. Conquista pela proximidade, pela simplicidade e pela falta de pose.",
    desejo: "Conectar-se com os outros.",
    meta: "Pertencer.",
    medo: "Destacar-se demais, ser excluído, parecer arrogante.",
    estrategia: "Cultivar virtudes simples e sólidas; ser acessível.",
    dom: "Realismo, empatia, ausência de pretensão.",
    armadilha: "Perder a identidade para se encaixar; virar “mais um”.",
    personalidade: ["Próximo", "Simples", "Confiável", "Bem-humorado", "Pé no chão", "Solidário"],
    tom: "Informal, direto e familiar. Papo de vizinho, exemplos do dia a dia, humor leve.",
    usa: ["a gente", "tipo assim", "na real", "sem frescura", "todo mundo", "de boa"],
    evita: ["termos rebuscados", "ostentação", "tom de superioridade", "jargão técnico"],
    frases: ["“Na real, é assim que funciona.”", "“Sem frescura.”", "“Se eu consegui, você também consegue.”", "“Aqui é gente como a gente.”", "“Bora trocar uma ideia?”"],
    roupas: "Estilo tradicional/casual: peças básicas e bem cuidadas. Jeans, camiseta, camisa xadrez, tênis. Azul, cinza, branco, tons neutros. Nada que pareça fantasia ou ostentação.",
    postura: "Relaxada, sorriso fácil, fala como numa conversa. Em vídeo: selfie, cenário real (casa, loja, rua), sem produção excessiva.",
    posicionamento: "“Feito por gente como você, para gente como você.” Diferencia-se por proximidade e preço justo.",
    conteudo: ["Bastidores reais, com erros e acertos", "Papo reto sobre dúvidas comuns", "Clientes de verdade", "Humor do cotidiano"],
    marcas: "IKEA, Levi's, Havaianas (fase “todo mundo usa”)",
    cuidado: "Simples não é genérico. Tenha pelo menos uma marca registrada que diferencie você."
  },
  AM: {
    lema: "Você é o único.",
    essencia: "Cria intimidade, beleza e prazer. Faz o cliente se sentir desejado, especial e cuidado nos detalhes.",
    desejo: "Intimidade e experiência sensorial.",
    meta: "Ter relações com as pessoas, o trabalho e os ambientes que ama.",
    medo: "Ficar sozinho, ser indesejado ou não amado.",
    estrategia: "Tornar-se cada vez mais atraente, física e emocionalmente.",
    dom: "Paixão, gratidão, apreço, compromisso.",
    armadilha: "Querer agradar a todos e perder a própria identidade.",
    personalidade: ["Apaixonado", "Sensível", "Caloroso", "Estético", "Envolvente", "Detalhista"],
    tom: "Sensorial, elegante, caloroso e envolvente. Descreve texturas, cheiros, sensações; fala baixo e próximo.",
    usa: ["sinta", "especial", "exclusivo", "prazer", "detalhe", "para você"],
    evita: ["tom frio e técnico", "pressa", "grosseria", "linguagem genérica"],
    frases: ["“Você merece viver isso.”", "“Cada detalhe foi pensado para você.”", "“Sinta a diferença.”", "“É sobre como você se sente.”", "“Feito com paixão.”"],
    roupas: "Estilo sensual/romântico: peças que valorizam o corpo, com caimento fluido. Vermelho, vinho, nude, dourado, preto. Seda, cetim, renda, camurça. Perfume, joias delicadas, detalhes de brilho.",
    postura: "Olhar próximo, fala suave, toque nos objetos. Em vídeo: closes, câmera lenta, luz quente e suave, profundidade de campo rasa.",
    posicionamento: "“Uma experiência que você sente.” Diferencia-se por estética, atenção e exclusividade.",
    conteudo: ["Detalhes em close (texturas, acabamentos)", "Experiências sensoriais", "Histórias de afeto e relação com clientes", "Rituais e cuidados"],
    marcas: "Chanel, Häagen-Dazs, Victoria's Secret",
    cuidado: "Encantar não é agradar a todos. Escolha o público que você quer seduzir."
  },
  BO: {
    lema: "Se eu não puder dançar, não quero fazer parte da sua revolução.",
    essencia: "Leva leveza e alegria. Quebra a seriedade e conecta pelo riso.",
    desejo: "Viver o momento com alegria plena.",
    meta: "Divertir-se e tornar o mundo mais leve.",
    medo: "Tédio; ser chato.",
    estrategia: "Brincar, fazer piadas, ser engraçado.",
    dom: "Alegria.",
    armadilha: "Frivolidade; desperdiçar a vida; não ser levado a sério.",
    personalidade: ["Divertido", "Espontâneo", "Irreverente", "Criativo", "Leve", "Sociável"],
    tom: "Divertido, rápido, criativo e inesperado. Usa trocadilhos, memes, autoironia.",
    usa: ["gente", "socorro", "bora", "real", "vish", "rindo aqui"],
    evita: ["tom solene", "textos longos e formais", "humor que humilha", "jargão"],
    frases: ["“Rindo pra não chorar.”", "“Quem nunca?”", "“Ninguém: … Eu: …”", "“Vida que segue, com humor.”", "“Leve a sério, mas não tanto.”"],
    roupas: "Estilo criativo e alegre: cores vibrantes, estampas, combinações inesperadas. Amarelo, laranja, azul-turquesa, pink. Camisetas com frases, tênis coloridos, meias divertidas, bonés.",
    postura: "Expressivo, gestos amplos, caretas, timing de comédia. Em vídeo: cortes rápidos, zoom, efeitos sonoros, legendas divertidas.",
    posicionamento: "“O jeito mais leve de resolver.” Diferencia-se por carisma e por ser lembrado.",
    conteudo: ["Humor e esquetes do dia a dia do setor", "Trends e memes adaptados", "Erros de gravação e bastidores", "Reações e desafios"],
    marcas: "M&M's, Fanta, Old Spice",
    cuidado: "Humor precisa servir à mensagem. Alterne com conteúdos que mostrem competência."
  },
  CU: {
    lema: "Ame o próximo como a si mesmo.",
    essencia: "Protege e cuida. Faz o cliente se sentir seguro, acolhido e amparado.",
    desejo: "Proteger os outros do mal.",
    meta: "Ajudar os outros.",
    medo: "Egoísmo e ingratidão.",
    estrategia: "Fazer coisas pelos outros.",
    dom: "Compaixão e generosidade.",
    armadilha: "Martírio; ser explorado; não saber dizer não.",
    personalidade: ["Empático", "Generoso", "Paciente", "Protetor", "Atento", "Confiável"],
    tom: "Acolhedor, responsável, atento e tranquilizador. Valida o sentimento antes de orientar.",
    usa: ["cuidar", "juntos", "você não está sozinho", "segurança", "apoio", "com calma"],
    evita: ["pressão de venda", "tom frio", "culpar o cliente", "urgência artificial"],
    frases: ["“Pode contar comigo.”", "“Você não está sozinho nisso.”", "“Vamos com calma, um passo de cada vez.”", "“Eu cuido disso pra você.”", "“O importante é você ficar bem.”"],
    roupas: "Estilo natural com toque romântico: peças confortáveis e acolhedoras. Tons quentes e suaves: bege, verde-sálvia, azul-claro, terracota. Algodão, tricô, malhas. Acessórios discretos.",
    postura: "Voz calma, sorriso sereno, corpo levemente inclinado para quem ouve. Em vídeo: luz quente, enquadramento próximo, ritmo tranquilo.",
    posicionamento: "“Quem cuida de você de verdade.” Diferencia-se por atenção, segurança e acompanhamento.",
    conteudo: ["Histórias de clientes ajudados", "Dicas de cuidado e prevenção", "Respostas acolhedoras a dúvidas", "Bastidores do atendimento"],
    marcas: "Johnson's Baby, Volvo, Unicef",
    cuidado: "Cuidar não é fazer de graça. Deixe claro o valor do seu trabalho e seus limites."
  },
  CR: {
    lema: "Se pode ser imaginado, pode ser criado.",
    essencia: "Cria algo original e duradouro. Expressa uma visão própria e valoriza o processo tanto quanto o resultado.",
    desejo: "Criar algo de valor duradouro.",
    meta: "Dar forma a uma visão.",
    medo: "Visão ou execução medíocre.",
    estrategia: "Desenvolver controle artístico e habilidade.",
    dom: "Criatividade e imaginação.",
    armadilha: "Perfeccionismo, projetos inacabados, soluções complicadas demais.",
    personalidade: ["Criativo", "Original", "Detalhista", "Expressivo", "Inventivo", "Perfeccionista"],
    tom: "Imaginativo, autoral, detalhista e estimulante. Mostra o raciocínio por trás da criação.",
    usa: ["criar", "processo", "autoral", "do zero", "ideia", "feito à mão"],
    evita: ["fórmulas prontas", "copiar tendências", "linguagem genérica", "“igual ao de todo mundo”"],
    frases: ["“Deixa eu te mostrar como isso nasceu.”", "“Nada aqui é de prateleira.”", "“Do rascunho ao resultado.”", "“A ideia veio de…”", "“Feito do zero, pensado para você.”"],
    roupas: "Estilo criativo: mistura autoral de peças, cores e texturas; uma assinatura visual própria. Paleta pessoal (muitas vezes preto com um ponto de cor). Tecidos com textura, peças de designers independentes, acessórios únicos.",
    postura: "Mãos em ação, mostrando o trabalho; fala entusiasmada sobre detalhes. Em vídeo: making of, planos detalhe, timelapse do processo.",
    posicionamento: "“Único, autoral, feito sob medida.” Diferencia-se por originalidade e assinatura estética.",
    conteudo: ["Processo criativo e making of", "Do rascunho ao resultado", "Referências e inspirações", "Projetos autorais e experimentos"],
    marcas: "LEGO, Adobe, Apple",
    cuidado: "O perfeito é inimigo do publicado. Defina um ritmo de entrega e cumpra."
  },
  GO: {
    lema: "O poder não é tudo, é a única coisa.",
    essencia: "Lidera com ordem, controle e excelência. Transmite segurança, estabilidade e prestígio.",
    desejo: "Controle.",
    meta: "Criar uma família, empresa ou comunidade próspera e bem-sucedida.",
    medo: "O caos; ser destituído.",
    estrategia: "Exercer liderança e poder.",
    dom: "Responsabilidade e liderança.",
    armadilha: "Autoritarismo; não conseguir delegar.",
    personalidade: ["Líder", "Organizado", "Exigente", "Seguro", "Responsável", "Sofisticado"],
    tom: "Seguro, formal, preciso e assertivo. Poucas palavras, afirmações firmes, números e referências.",
    usa: ["excelência", "padrão", "liderança", "garantia", "resultado", "exclusivo"],
    evita: ["gírias", "hesitação", "humor excessivo", "informalidade demais"],
    frases: ["“Aqui existe um padrão.”", "“Deixe comigo, está sob controle.”", "“Qualidade não se negocia.”", "“Cada detalhe tem um processo.”", "“Nós definimos a referência.”"],
    roupas: "Estilo elegante com urbano dramático: alfaiataria de excelente caimento. Preto, azul-marinho, cinza-chumbo, branco, dourado discreto. Lã fria, algodão egípcio, couro. Relógio clássico, sapato impecável, poucos e bons acessórios.",
    postura: "Postura ereta, movimentos econômicos, olhar direto, voz grave e pausada. Em vídeo: enquadramento simétrico, cenário sóbrio, luz controlada.",
    posicionamento: "“A referência do mercado.” Diferencia-se por autoridade, qualidade premium e segurança.",
    conteudo: ["Cases e números", "Bastidores de uma operação impecável", "Opinião de autoridade sobre o setor", "Padrões e processos"],
    marcas: "Rolex, Mercedes-Benz, Montblanc",
    cuidado: "Autoridade sem proximidade vira distância. Mostre as pessoas e a visão por trás do controle."
  }
};

window.FONTES = [
  {t: "Mark, M. & Pearson, C. S. O Herói e o Fora-da-Lei: como construir marcas extraordinárias usando o poder dos arquétipos. Cultrix, 2003 (orig. McGraw-Hill, 2001).", u: "https://books.google.com/books/about/The_Hero_and_the_Outlaw_Building_Extraor.html?id=l6qXGiTld1sC", uso: "Modelo dos 12 arquétipos: desejo, meta, medo, estratégia, dom, armadilha e lema."},
  {t: "Pearson, C. S. O Despertar do Herói Interior. Pensamento, 1994 (orig. 1991), e o Pearson-Marr Archetype Indicator (PMAI).", u: "https://carolspearson.com/about/archetypal-assessment-pearson-marr-archetype-indicator-r", uso: "Base psicológica dos arquétipos e formato de avaliação por escala."},
  {t: "Aaker, J. L. Dimensions of Brand Personality. Journal of Marketing Research, 1997.", u: "https://doi.org/10.1177/002224379703400304", uso: "Fundamento acadêmico de personalidade de marca."},
  {t: "Jeffrey, S. 12 Brand Archetypes: Complete Guide & Archetype Wheel.", u: "https://scottjeffrey.com/12-brand-archetype-wheel/", uso: "Tom de voz, dons, sombras e exemplos de marcas."},
  {t: "Ignyte Brands. How to Unlock the Power of Brand Archetypes.", u: "https://www.ignytebrands.com/unlocking-the-power-of-brand-archetypes/", uso: "Forças, fraquezas e exemplos de marcas."},
  {t: "Amper. Arquétipos de marca: o guia atualizado dos 12 perfis.", u: "https://www.amper.ag/post/arquetipos-de-marca-1", uso: "Tom de voz, vocabulário e estética em português."},
  {t: "Citera, P. Os 12 arquétipos de Jung e o estilo pessoal. Vestindo Autoestima.", u: "https://vestindoautoestima.com.br/os-12-arquetipos-de-jung-e-o-estilo-pessoal/", uso: "Relação entre arquétipos e os estilos universais de roupa."}
];
window.NOTA_FONTES = "Desejo, meta, medo, estratégia, dom, armadilha e lema seguem Mark & Pearson. Tom de voz, vocabulário e estilo de roupa vêm dos guias citados. Frases típicas, postura em vídeo e ideias de conteúdo são aplicações práticas da 3P's Produções a partir dessas bases. Os exemplos de marcas são ilustrativos.";
